apiVersion: apps/v1
kind: Deployment
metadata:
  name: MYAPP
  namespace: sai
  labels:
    app: MYAPP
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MYAPP
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      imagePullSecrets:
        - name: acr-alex
      containers:
      - name: MYAPP
        image: munna2218.azurecr.io/munna2218:1.0.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: MYAPP-config
              key: DB_HOST
        ports:
        - containerPort: 80
          name: MYAPP
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
